In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("datasets/Minimum Wage Data.csv",encoding = "latin")

In [4]:
df.to_csv("datasets/minwage.csv", encoding= "utf-8")

In [5]:
df = pd.read_csv("datasets/minwage.csv")

In [6]:
df.head()

,Unnamed: 0,Year,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
0,0,1968,Alabama,0.00000,0.00,1.15,8.55,1.15,8.55,34.8,...,0.00000,0.00,0.00000,0.00,NaN
1,1,1968,Alaska,2.10000,15.61,1.15,8.55,2.10,15.61,34.8,2.1,2.10000,15.61,2.10000,15.61,NaN
2,2,1968,Arizona,0.46800,3.48,1.15,8.55,1.15,8.55,34.8,18.72 - 26.40/wk(b),0.46800,3.48,0.66000,4.91,(b)
3,3,1968,Arkansas,0.15625,1.16,1.15,8.55,1.15,8.55,34.8,1.25/day(b),0.15625,1.16,0.15625,1.16,(b)
4,4,1968,California,1.65000,12.26,1.15,8.55,1.65,12.26,34.8,1.65(b),1.65000,12.26,1.65000,12.26,(b)

In [8]:
gb = df.groupby("State")

In [9]:
gb.get_group("Alabama").set_index("Year").head()

,Unnamed: 0,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
Year,,,,,,,,,,,,,,,
1968,0,Alabama,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN
1969,54,Alabama,0.0,0.0,1.15,8.11,1.15,8.11,36.7,...,0.0,0.0,0.0,0.0,NaN
1970,108,Alabama,0.0,0.0,1.30,8.67,1.30,8.67,38.8,...,0.0,0.0,0.0,0.0,NaN
1971,162,Alabama,0.0,0.0,1.30,8.30,1.30,8.30,40.5,...,0.0,0.0,0.0,0.0,NaN
1972,216,Alabama,0.0,0.0,1.60,9.90,1.60,9.90,41.8,...,0.0,0.0,0.0,0.0,NaN

In [10]:
act_min_wage = pd.DataFrame()

In [33]:
for name, group in df.groupby("State"):
    if act_min_wage.empty:
        act_min_wage = group.set_index("Year")[["Department.Of.Labor.Cleaned.Low.Value.2020.Dollars"]].rename(columns={"Department.Of.Labor.Cleaned.Low.Value.2020.Dollars":name})
    else:
        act_min_wage = act_min_wage.join(group.set_index("Year")[["Department.Of.Labor.Cleaned.Low.Value.2020.Dollars"]].rename(columns={"Department.Of.Labor.Cleaned.Low.Value.2020.Dollars":name}))

act_min_wage.head()

ValueError: columns overlap but no suffix specified: Index(['Alabama'], dtype='object')

In [17]:
act_min_wage,

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
count,53.0,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,...,53.0,53.000000,42.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,0.0,9.917736,2.917358,7.139245,9.101132,6.881698,9.212830,7.818679,8.919245,2.415283,...,0.0,5.816038,6.980238,7.079245,9.057358,6.163019,8.826038,7.486226,7.914528,5.313208
std,0.0,1.852213,4.102247,1.459132,1.418712,1.921086,1.106907,1.307834,1.932959,3.882305,...,0.0,2.240879,1.815899,0.824707,1.093119,2.749633,2.147933,0.866017,0.778113,2.004899
min,0.0,7.620000,0.000000,1.100000,6.630000,3.970000,7.040000,4.550000,5.690000,0.000000,...,0.0,0.000000,4.430000,4.950000,7.030000,0.000000,4.550000,5.770000,6.630000,2.340000
25%,0.0,8.590000,0.000000,6.780000,8.000000,5.250000,8.200000,7.320000,7.420000,0.000000,...,0.0,4.990000,5.225000,6.610000,8.060000,6.250000,7.610000,6.850000,7.320000,3.500000
50%,0.0,9.260000,0.000000,7.210000,9.010000,6.670000,9.430000,8.170000,8.840000,0.000000,...,0.0,6.360000,7.105000,7.220000,9.240000,7.210000,9.700000,7.370000,7.810000,5.550000
75%,0.0,10.510000,8.290000,7.740000,9.710000,8.430000,9.870000,8.620000,9.600000,8.210000,...,0.0,7.350000,8.270000,7.660000,9.820000,7.810000,10.180000,7.930000,8.340000,6.820000
max,0.0,15.610000,12.140000,10.000000,13.000000,12.140000,11.450000,9.900000,14.160000,8.790000,...,0.0,8.660000,10.620000,8.600000,11.090000,9.090000,13.660000,9.430000,9.980000,9.280000

In [19]:
act_min_wage.corr()

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alaska,NaN,1.000000,0.037101,-0.332127,0.622245,-0.078678,0.646909,0.260265,0.271810,-0.193062,...,NaN,-0.507366,0.305388,-0.017546,0.615675,-0.593675,0.378141,0.056924,0.683108,0.726771
Arizona,NaN,0.037101,1.000000,0.271834,0.639006,0.820730,0.555455,0.477781,0.723523,0.907295,...,NaN,0.398732,-0.421255,0.413915,0.624314,0.096048,0.691863,0.663311,0.014723,0.288171
Arkansas,NaN,-0.332127,0.271834,1.000000,0.030265,0.333597,0.183662,0.107639,0.433775,0.340509,...,NaN,0.520381,0.080528,0.208586,0.236875,0.572595,0.130825,0.504703,-0.069024,-0.235369
California,NaN,0.622245,0.639006,0.030265,1.000000,0.649967,0.881831,0.518481,0.727373,0.443946,...,NaN,-0.109316,-0.061610,0.367924,0.894617,-0.216247,0.816087,0.492809,0.382444,0.598739
Colorado,NaN,-0.078678,0.820730,0.333597,0.649967,1.000000,0.520931,0.581162,0.798145,0.764719,...,NaN,0.375583,-0.343366,0.538775,0.581318,0.229610,0.721208,0.623479,-0.101133,0.095454
Connecticut,NaN,0.646909,0.555455,0.183662,0.881831,0.520931,1.000000,0.586472,0.700081,0.401571,...,NaN,0.106585,-0.192918,0.307922,0.911003,-0.248514,0.760697,0.484080,0.468287,0.752009
Delaware,NaN,0.260265,0.477781,0.107639,0.518481,0.581162,0.586472,1.000000,0.742080,0.372261,...,NaN,0.396561,-0.466054,0.503722,0.527217,-0.137181,0.820178,0.477105,0.024637,0.484522
District of Columbia,NaN,0.271810,0.723523,0.433775,0.727373,0.798145,0.700081,0.742080,1.000000,0.603776,...,NaN,0.298301,-0.269490,0.463232,0.773468,0.074135,0.844603,0.706347,0.085788,0.328834
Florida,NaN,-0.193062,0.907295,0.340509,0.443946,0.764719,0.401571,0.372261,0.603776,1.000000,...,NaN,0.515836,-0.544537,0.430381,0.509489,0.340376,0.575505,0.656734,-0.061231,0.149554
Georgia,NaN,-0.567726,0.084376,0.442474,-0.318568,0.157845,-0.072117,0.321689,0.076393,0.236443,...,NaN,0.927752,-0.489470,0.124733,-0.228677,0.346082,-0.000988,0.185003,-0.434365,-0.098952
Guam,NaN,0.787515,0.044794,0.037006,0.411729,-0.152291,0.587469,0.173421,0.258940,-0.175103,...,NaN,-0.211959,0.316188,0.099315,0.504418,-0.448941,0.195535,0.138478,0.726536,0.542144
Hawaii,NaN,0.630212,0.342798,0.324870,0.610784,0.291995,0.674581,0.505127,0.682666,0.193478,...,NaN,-0.037298,-0.003708,0.126257,0.745415,-0.122713,0.591754,0.504798,0.467383,0.544010
Idaho,NaN,0.371745,0.402623,0.008276,0.542006,0.436981,0.536894,0.695469,0.541039,0.290963,...,NaN,0.100972,-0.267393,0.844135,0.532401,-0.124374,0.708873,0.379467,0.362122,0.396824
Illinois,NaN,-0.556841,0.314497,0.668883,-0.167283,0.320527,0.021930,0.242373,0.246534,0.490635,...,NaN,0.898832,-0.484943,0.351901,0.020297,0.664935,0.116154,0.515523,-0.183853,-0.223443
Indiana,NaN,0.354060,0.629321,-0.049715,0.736715,0.612062,0.725477,0.681547,0.600315,0.530048,...,NaN,0.129779,-0.498190,0.664460,0.691381,-0.172164,0.833978,0.415412,0.237954,0.568333
Iowa,NaN,-0.575077,0.419232,0.322346,0.044122,0.603350,-0.076988,0.428771,0.365778,0.551091,...,NaN,0.515781,-0.478841,0.685914,0.014848,0.522858,0.426896,0.385991,-0.452995,-0.303209
Kansas,NaN,-0.535432,0.524711,0.428403,0.101287,0.590171,-0.022415,-0.038572,0.293030,0.648743,...,NaN,0.460560,-0.252140,0.531121,0.114905,0.667136,0.153774,0.498768,-0.201143,-0.430025
Kentucky,NaN,-0.558293,0.305474,0.441958,-0.054002,0.474155,-0.114716,0.223943,0.270809,0.497980,...,NaN,0.527370,-0.453647,0.551383,0.072892,0.837286,0.211133,0.617748,-0.197694,-0.421230
Louisiana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Maine,NaN,0.642685,0.414491,0.192072,0.804847,0.433139,0.715533,0.281036,0.611173,0.253267,...,NaN,-0.232463,0.299946,0.173951,0.837959,-0.018769,0.604054,0.485251,0.509900,0.451237
Maryland,NaN,0.420479,0.428242,0.555619,0.568976,0.321538,0.633147,0.167655,0.585907,0.270628,...,NaN,0.125887,0.339672,0.261080,0.674610,0.110363,0.373055,0.584949,0.513456,0.213820
Massachusetts,NaN,0.618329,0.621933,0.116806,0.957473,0.652008,0.901362,0.564434,0.773951,0.411755,...,NaN,-0.037643,-0.040408,0.321376,0.899971,-0.208882,0.801829,0.534225,0.370725,0.575660
Michigan,NaN,0.590455,0.481035,0.213170,0.681970,0.318337,0.771777,0.200472,0.467803,0.336967,...,NaN,0.008801,0.007677,0.182321,0.776777,-0.042952,0.407404,0.558787,0.719225,0.506710
Minnesota,NaN,-0.363881,-0.103119,0.496147,-0.130918,0.091370,-0.234686,-0.339677,0.012000,0.046488,...,NaN,0.093295,0.630647,0.125349,-0.042020,0.774366,-0.222781,0.371486,-0.007897,-0.642386
Mississippi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Missouri,NaN,-0.545246,0.498831,0.370757,0.129542,0.687465,0.003106,0.459599,0.452698,0.613422,...,NaN,0.529685,-0.457718,0.674731,0.096714,0.525831,0.491585,0.439321,-0.441635,-0.270738
Montana,NaN,-0.366100,0.068680,0.598666,-0.211595,0.109280,-0.046493,0.178376,0.242511,0.107074,...,NaN,0.710841,0.166788,0.133819,-0.133488,0.340565,-0.058940,0.302088,-0.242749,-0.310200
Nebraska,NaN,-0.118830,0.602870,0.291749,0.372427,0.760798,0.291186,0.763090,0.756945,0.588463,...,NaN,0.466796,-0.470155,0.613436,0.391142,0.297447,0.674042,0.690394,-0.201771,0.012383
Nevada,NaN,0.701426,0.083415,-0.054490,0.374463,-0.012322,0.534085,0.507303,0.313822,-0.076942,...,NaN,-0.050612,-0.004203,0.350648,0.509543,-0.273114,0.371622,0.301348,0.763468,0.549069
New Hampshire,NaN,0.792106,-0.088632,-0.250984,0.350228,-0.236722,0.420869,0.032651,0.011219,-0.259449,...,NaN,-0.432301,0.326303,0.134927,0.429021,-0.343659,0.070235,0.115325,0.890565,0.461103
New Jersey,NaN,0.645369,0.463305,0.111088,0.724435,0.319119,0.602805,0.274204,0.557387,0.286040,...,NaN,-0.275224,0.324144,0.258919,0.736683,-0.117432,0.545623,0.483265,0.604300,0.369958
New Mexico,NaN,0.503251,0.571500,0.159904,0.596597,0.351780,0.584606,0.267230,0.520522,0.452691,...,NaN,-0.006935,-0.017682,0.297228,0.733913,0.038951,0.476473,0.636525,0.608179,0.423926
New York,NaN,0.803937,0.484419,-0.019945,0.814327,0.275604,0.810524,0.360023,0.562728,0.266468,...,NaN,-0.158150,0.168866,0.085864,0.802303,-0.407078,0.589843,0.365417,0.543789,0.672775
North Carolina,NaN,0.447145,0.215386,0.343342,0.322187,0.110615,0.546608,0.319959,0.344164,0.139054,...,NaN,0.116745,-0.106321,0.436009,0.565424,0.070927,0.274934,0.500789,0.797673,0.388642
North Dakota,NaN,-0.002115,0.200862,0.291886,0.185905,0.266788,0.117157,0.184424,0.300013,0.294139,...,NaN,0.088374,-0.152652,0.718744,0.384965,0.693063,0.314656,0.682873,0.417059,-0.144383
Ohio,NaN,-0.159050,0.643697,0.383000,0.232309,0.483689,0.077804,0.131838,0.384183,0.648466,...,NaN,0.292859,-0.036390,0.555703,0.317751,0.521108,0.306637,0.667465,0.194485,-0.202383
Oklahoma,NaN,0.278029,-0.708424,-0.310780,-0.427373,-0.763597,-0.411766,-0.458547,-0.557976,-0.801164,...,NaN,-0.491892,0.658181,-0.392828,-0.455545,-0.362779,-0.637575,-0.512307,0.277606,-0.172678
Oregon,NaN,0.010495,0.597412,0.399650,0.572160,0.733803,0.480491,0.546410,0.717969,0.652549,...,NaN,0.303448,-0.350875,0.669620,0.664231,0.541823,0.758025,0.785371,0.116662,0.102129
Pennsylvania,NaN,0.590298,-0.031127,0.065998,0.241669,-0.229508,0.408964,-0.011283,-0.009684,-0.133604,...,NaN,-0.174104,0.265243,0.200819,0.410226,-0.102701,0.017676,0.216993,0.907332,0.375716
Puerto Rico,NaN,0.052368,0.602170,0.337474,0.610931,0.629561,0.705002,0.462204,0.572458,0.651141,...,NaN,0.423151,-0.466373,0.338753,0.651566,0.215202,0.643443,0.561718,0.015987,0.375641
Rhode Island,NaN,0.610099,0.554561,0.160773,0.816544,0.559646,0.829952,0.778867,0.837786,0.390880,...,NaN,0.047797,-0.316936,0.339743,0.860679,-0.187019,0.866566,0.577176,0.301237,0.630303
South Carolina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Dakota,NaN,-0.287259,0.447113,0.826094,0.171242,0.519677,0.228521,0.374813,0.613463,0.533627,...,NaN,0.569014,-0.230335,0.587963,0.377357,0.699797,0.420561,0.747518,-0.029574,-0.190646
Tennessee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,NaN,-0.507366,0.398732,0.520381,-0.109316,0.375583,0.106585,0.396561,0.298301,0.515836,...,NaN,1.000000,-0.616811,0.289986,0.000040,0.403861,0.185268,0.435600,-0.334920,-0.027358
U.S. Virgin Islands,NaN,0.305388,-0.421255,0.080528,-0.061610,-0.343366,-0.192918,-0.466054,-0.269490,-0.544537,...,NaN,-0.616811,1.000000,-0.240246,-0.198319,-0.268294,-0.346363,-0.355199,0.188345,-0.439579
Utah,NaN,-0.017546,0.413915,0.208586,0.367924,0.538775,0.307922,0.503722,0.463232,0.430381,...,NaN,0.289986,-0.240246,1.000000,0.398996,0.364400,0.560994,0.555480,0.251923,0.005837
Vermont,NaN,0.615675,0.624314,0.236875,0.894617,0.581318,0.911003,0.527217,0.773468,0.509489,...,NaN,0.000040,-0.198319,0.398996,1.000000,-0.015547,0.801069,0.649423,0.533349,0.622181
Virginia,NaN,-0.593675,0.096048,0.572595,-0.216247,0.229610,-0.248514,-0.137181,0.074135,0.340376,...,NaN,0.403861,-0.268294,0.364400,-0.015547,1.000000,-0.053308,0.533227,-0.080277,-0.545553
Washington,NaN,0.378141,0.691863,0.130825,0.816087,0.721208,0.760697,0.820178,0.844603,0.575505,...,NaN,0.185268,-0.346363,0.560994,0.801069,-0.053308,1.000000,0.573635,0.134650,0.544957
West Virginia,NaN,0.056924,0.663311,0.504703,0.492809,0.623479,0.484080,0.477105,0.706347,0.656734,...,NaN,0.435600,-0.355199,0.555480,0.649423,0.533227,0.573635,1.000000,0.269653,0.087201
Wisconsin,NaN,0.683108,0.014723,-0.069024,0.382444,-0.101133,0.468287,0.024637,0.085788,-0.061231,...,NaN,-0.334920,0.188345,0.251923,0.533349,-0.080277,0.134650,0.269653,1.000000,0.407841
Wyoming,NaN,0.726771,0.288171,-0.235369,0.598739,0.095454,0.752009,0.484522,0.328834,0.149554,...,NaN,-0.027358,-0.439579,0.005837,0.622181,-0.545553,0.544957,0.087201,0.407841,1.000000

In [21]:
act_min_wage.corr().head()

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alaska,NaN,1.000000,0.037101,-0.332127,0.622245,-0.078678,0.646909,0.260265,0.271810,-0.193062,...,NaN,-0.507366,0.305388,-0.017546,0.615675,-0.593675,0.378141,0.056924,0.683108,0.726771
Arizona,NaN,0.037101,1.000000,0.271834,0.639006,0.820730,0.555455,0.477781,0.723523,0.907295,...,NaN,0.398732,-0.421255,0.413915,0.624314,0.096048,0.691863,0.663311,0.014723,0.288171
Arkansas,NaN,-0.332127,0.271834,1.000000,0.030265,0.333597,0.183662,0.107639,0.433775,0.340509,...,NaN,0.520381,0.080528,0.208586,0.236875,0.572595,0.130825,0.504703,-0.069024,-0.235369
California,NaN,0.622245,0.639006,0.030265,1.000000,0.649967,0.881831,0.518481,0.727373,0.443946,...,NaN,-0.109316,-0.061610,0.367924,0.894617,-0.216247,0.816087,0.492809,0.382444,0.598739

In [22]:
df.head()

,Unnamed: 0,Year,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
0,0,1968,Alabama,0.00000,0.00,1.15,8.55,1.15,8.55,34.8,...,0.00000,0.00,0.00000,0.00,NaN
1,1,1968,Alaska,2.10000,15.61,1.15,8.55,2.10,15.61,34.8,2.1,2.10000,15.61,2.10000,15.61,NaN
2,2,1968,Arizona,0.46800,3.48,1.15,8.55,1.15,8.55,34.8,18.72 - 26.40/wk(b),0.46800,3.48,0.66000,4.91,(b)
3,3,1968,Arkansas,0.15625,1.16,1.15,8.55,1.15,8.55,34.8,1.25/day(b),0.15625,1.16,0.15625,1.16,(b)
4,4,1968,California,1.65000,12.26,1.15,8.55,1.65,12.26,34.8,1.65(b),1.65000,12.26,1.65000,12.26,(b)

In [24]:
issue_df = df[df['Department.Of.Labor.Cleaned.Low.Value.2020.Dollars']==0]

In [25]:
issue_df.head()

,Unnamed: 0,Year,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
0,0,1968,Alabama,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN
9,9,1968,Florida,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN
10,10,1968,Georgia,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN
14,14,1968,Illinois,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN
16,16,1968,Iowa,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN

In [26]:
issue_df["State"].unique

<bound method Series.unique of 0              Alabama
9              Florida
10             Georgia
14            Illinois
16                Iowa
             ...
2808           Alabama
2827         Louisiana
2833       Mississippi
2850    South Carolina
2852         Tennessee
Name: State, Length: 415, dtype: object>

In [27]:
import numpy as np

In [29]:
act_min_wage.replace(0,np.NaN).dropna(axis = 1).corr().head()

,Alaska,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Guam,Hawaii,Idaho,...,Oregon,Pennsylvania,Rhode Island,South Dakota,Utah,Vermont,Washington,West Virginia,Wisconsin,Wyoming
Alaska,1.000000,-0.332127,0.622245,-0.078678,0.646909,0.260265,0.271810,0.787515,0.630212,0.371745,...,0.010495,0.590298,0.610099,-0.287259,-0.017546,0.615675,0.378141,0.056924,0.683108,0.726771
Arkansas,-0.332127,1.000000,0.030265,0.333597,0.183662,0.107639,0.433775,0.037006,0.324870,0.008276,...,0.399650,0.065998,0.160773,0.826094,0.208586,0.236875,0.130825,0.504703,-0.069024,-0.235369
California,0.622245,0.030265,1.000000,0.649967,0.881831,0.518481,0.727373,0.411729,0.610784,0.542006,...,0.572160,0.241669,0.816544,0.171242,0.367924,0.894617,0.816087,0.492809,0.382444,0.598739
Colorado,-0.078678,0.333597,0.649967,1.000000,0.520931,0.581162,0.798145,-0.152291,0.291995,0.436981,...,0.733803,-0.229508,0.559646,0.519677,0.538775,0.581318,0.721208,0.623479,-0.101133,0.095454
Connecticut,0.646909,0.183662,0.881831,0.520931,1.000000,0.586472,0.700081,0.587469,0.674581,0.536894,...,0.480491,0.408964,0.829952,0.228521,0.307922,0.911003,0.760697,0.484080,0.468287,0.752009

In [36]:
min_wage_corr = act_min_wage.replace(0,np.NaN).dropna(axis = 1).corr().head()
for problem in issue_df['State'].unique():
    if problem in min_wage_corr.columns:
        print("data missing?")

In [31]:
grouped_issues = issue_df.groupby("State")
grouped_issues.get_group("Alabama").head(3)

,Unnamed: 0,Year,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
0,0,1968,Alabama,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN
54,54,1969,Alabama,0.0,0.0,1.15,8.11,1.15,8.11,36.7,...,0.0,0.0,0.0,0.0,NaN
108,108,1970,Alabama,0.0,0.0,1.30,8.67,1.30,8.67,38.8,...,0.0,0.0,0.0,0.0,NaN

In [37]:
for state, data in grouped_issues:
    if data["Department.Of.Labor.Cleaned.Low.Value.2020.Dollars"].sum()!= 0.0:
        print("bogus")